// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Qk-BgU0LKcOCFFlFdvvfbtd5NJevMEA',
    appId: '1:107289472326:web:99bd001472c6f5b6408947',
    messagingSenderId: '107289472326',
    projectId: 'mindsetforge-ai',
    authDomain: 'mindsetforge-ai.firebaseapp.com',
    storageBucket: 'mindsetforge-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy8wMMCyeiYAYgbDyIoRTpNMFdWuStfrs',
    appId: '1:107289472326:android:0f22fae319f37f34408947',
    messagingSenderId: '107289472326',
    projectId: 'mindsetforge-ai',
    storageBucket: 'mindsetforge-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3VmHdryU9TP7F7Ifxb3tTW3LvSXc6Qs4',
    appId: '1:107289472326:ios:43b4e2ab75f56591408947',
    messagingSenderId: '107289472326',
    projectId: 'mindsetforge-ai',
    storageBucket: 'mindsetforge-ai.firebasestorage.app',
    iosBundleId: 'com.mindsetforge.mindsetforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3VmHdryU9TP7F7Ifxb3tTW3LvSXc6Qs4',
    appId: '1:107289472326:ios:43b4e2ab75f56591408947',
    messagingSenderId: '107289472326',
    projectId: 'mindsetforge-ai',
    storageBucket: 'mindsetforge-ai.firebasestorage.app',
    iosBundleId: 'com.mindsetforge.mindsetforge',
  );
}
